//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;
use async_graphql::SimpleObject;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, SimpleObject, Deserialize, Serialize)]
#[sea_orm(table_name = "stock_order_entity")]
#[graphql(name = "StockOrderEntity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Float")]
    pub bid_price: f32,
    pub bid_size: i32,
    pub order_type: String,
    pub created_at: DateTime,
    pub deleted_at: DateTime,
}

pub type StockOrderEntity = Model;

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
